name: Builder

on:
  workflow_dispatch:
    inputs:
      GIT_URL:
        description: "Git URL"
        default: "https://github.com/RIPE-NCC/ripe-atlas-software-probe.git"
        required: true
      BRANCH:
        description: "Branch To Clone"
        default: "master"
        required: true

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Git Clone
        run: git clone --recursive "${{ github.event.inputs.GIT_URL }}" --branch "${{ github.event.inputs.BRANCH }}"

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y git tar fakeroot libssl-dev libcap2-bin autoconf automake libtool build-essential
          dpkg-buildpackage -b -us -uc
          
      - name: Upload to file.io
        run: |
          FILE_NAME="$(ls *.deb)"
          curl -F "file=@${FILE_NAME}" https://file.io

      - uses: actions/upload-artifact@v4
        with:
            name: Built Deb File
            path: ./*.deb
