name: Builder

on:
  workflow_dispatch:
    inputs:
      GIT_URL:
        description: "Git URL"
        default: "https://github.com/RIPE-NCC/ripe-atlas-software-probe.git"
        required: true
      BRANCH:
        description: "Branch To Clone"
        default: "master"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - name: Install required packages
        run: |
          apt-get update
          apt-get install --yes git build-essential debhelper libssl-dev autotools-dev psmisc net-tools systemd

      - name: Clone Git Repository
        run: git clone --recursive "${{ github.event.inputs.GIT_URL }}" --branch "${{ github.event.inputs.BRANCH }}" ripe-atlas-software-probe

      - name: Build the Deb File
        run: |
          pushd ripe-atlas-software-probe
          git checkout master
          dpkg-buildpackage -b -us -uc
          cp ../ripe-atlas-*.deb .
          pushd .repo
          dpkg-buildpackage -b -us -uc
          popd
          
      # - name: Upload to file.io
      #   run: |
      #     cd ripe-atlas-software-probe
      #     TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
      #     FILE_NAME="ripe-atlas-probe_${TAG}_all.deb"
      #     curl -F "file=@${FILE_NAME}" https://file.io

      - uses: actions/upload-artifact@v4
        with:
            name: Built Deb File
            path: ./*.deb
