name: Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@v2
        with:
            name: Built Deb File
            path: ./*.deb
